version: '3.5'
services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    container_name: ambassadorAdmin_nginx

  app:
    build:
      context: ./
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 8080:8080
    container_name: ambassadorAdmin_app
